from django.db import models

class CallingPlan(models.Model):
    company = models.CharField('사업자', max_length=20, null=False)
    brand = models.CharField('브랜드', max_length=20, null=False)
    homepage = models.URLField('홈페이지')
    calling_plan = models.CharField('요금제명', max_length=100, null=False)
    mobile_carrier = models.CharField('통신사', max_length=20, choices=(('LGU+','LGU+'),('SKT','SKT'),('KT','KT')))
    category = models.CharField('종류', max_length=20, choices=(('usim','usim'),('tablet','tablet'),('phone','phone')))
    data_speed = models.CharField('통신 속도', max_length=10, choices=(('LTE','LTE'),('3G','3G'),('5G','5G')))
    data_category = models.IntegerField('데이터 기준')
    data_unit = models.CharField('데이터 단위', max_length=5, choices=(('월','월'),('일','일')))
    call = models.IntegerField('음성')
    call_unit = models.CharField('음성 단위', max_length=5, choices=(('분','분'),('윙','윙')))
    unlimited_free = models.CharField('망내 무료', max_length=5, choices=(('Y','Y'),('N','N')))
    message = models.IntegerField('문자')
    message_unit = models.CharField('문자 단위', max_length=5, choices=(('건','건'),('윙','윙')))
    data1 = models.CharField('월데이터1', max_length=10)
    data2 = models.CharField('월데이터2', max_length=100, null=True, blank=True)
    pay = models.IntegerField('기본료')
    promo_pay = models.IntegerField('할인 기본료')
    saled_pay1 = models.IntegerField('제휴카드할인시 월요금1', null=True, blank=True, default=0)
    saled_pay2 = models.IntegerField('제휴카드할인시 월요금2', null=True, blank=True, default=0)
    saled_pay3 = models.IntegerField('제휴카드할인시 월요금3', null=True, blank=True, default=0)
    sales_pay1 = models.IntegerField('제휴카드 금액1', null=True, blank=True, default=0)
    condition1 = models.IntegerField('제휴카드 요건1', null=True, blank=True, default=0)
    sales_pay2 = models.IntegerField('제휴카드 금액2', null=True, blank=True, default=0)
    condition2 = models.IntegerField('제휴카드 요건2', null=True, blank=True, default=0)
    sales_pay3 = models.IntegerField('제휴카드 금액3', null=True, blank=True, default=0)
    condition3 = models.IntegerField('제휴카드 요건3', null=True, blank=True, default=0)
    etc1 = models.CharField('특이사항1', max_length=100, null=True, blank=True)
    etc2 = models.CharField('특이사항2', max_length=100, null=True, blank=True)
    etc3 = models.CharField('특이사항3', max_length=100, null=True, blank=True)
    activation = models.CharField('활성화 여부', max_length=5, choices=(('Y','Y'),('N','N')))
    update_date = models.DateTimeField('업데이트 날짜', auto_now=True, null=True, blank=True)
    create_date = models.DateTimeField('생성 날짜', auto_now_add=True)

class CVSUpload(models.Model):
    file = models.FileField('파일', upload_to='epost/%Y/%m/%d')
    date = models.DateTimeField('업로드 날짜', auto_now_add=True)