# Generated by Django 2.2.4 on 2020-02-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, verbose_name='사업자')),
                ('brand', models.CharField(max_length=20, verbose_name='브랜드')),
                ('homepage', models.URLField(verbose_name='홈페이지')),
                ('calling_plan', models.CharField(max_length=100, verbose_name='요금제명')),
                ('mobile_carrier', models.CharField(choices=[('LGU+', 'LGU+'), ('SKT', 'SKT'), ('KT', 'KT')], max_length=20, verbose_name='통신사')),
                ('category', models.CharField(choices=[('usim', 'usim'), ('tablet', 'tablet'), ('phone', 'phone')], max_length=20, verbose_name='종류')),
                ('data_speed', models.CharField(choices=[('LTE', 'LTE'), ('3G', '3G'), ('5G', '5G')], max_length=10, verbose_name='통신 속도')),
                ('data_category', models.CharField(max_length=10, verbose_name='데이터 기준')),
                ('data_unit', models.CharField(choices=[('월', '월'), ('일', '일')], max_length=5, verbose_name='데이터 단위')),
                ('call', models.CharField(max_length=10, verbose_name='음성')),
                ('call_unit', models.CharField(choices=[('분', '분'), ('윙', '윙')], max_length=5, verbose_name='음성 단위')),
                ('unlimited_free', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=5, verbose_name='망내 무료')),
                ('message', models.CharField(max_length=10, verbose_name='문자')),
                ('message_unit', models.CharField(choices=[('건', '건'), ('윙', '윙')], max_length=5, verbose_name='문자 단위')),
                ('data1', models.CharField(max_length=10, verbose_name='월데이터1')),
                ('data2', models.CharField(blank=True, max_length=100, null=True, verbose_name='월데이터2')),
                ('pay', models.IntegerField(verbose_name='기본료')),
                ('promo_pay', models.IntegerField(verbose_name='할인 기본료')),
                ('saled_pay1', models.IntegerField(blank=True, default=0, null=True, verbose_name='제휴카드할인시 월요금1')),
                ('saled_pay2', models.IntegerField(blank=True, default=0, null=True, verbose_name='제휴카드할인시 월요금2')),
                ('saled_pay3', models.IntegerField(blank=True, default=0, null=True, verbose_name='제휴카드할인시 월요금3')),
                ('sales_pay1', models.IntegerField(blank=True, default=0, null=True, verbose_name='제휴카드 금액1')),
                ('condition1', models.IntegerField(blank=True, default=0, null=True, verbose_name='제휴카드 요건1')),
                ('sales_pay2', models.IntegerField(blank=True, default=0, null=True, verbose_name='제휴카드 금액2')),
                ('condition2', models.IntegerField(blank=True, default=0, null=True, verbose_name='제휴카드 요건2')),
                ('sales_pay3', models.IntegerField(blank=True, default=0, null=True, verbose_name='제휴카드 금액3')),
                ('condition3', models.IntegerField(blank=True, default=0, null=True, verbose_name='제휴카드 요건3')),
                ('etc1', models.CharField(blank=True, max_length=100, null=True, verbose_name='특이사항1')),
                ('etc2', models.CharField(blank=True, max_length=100, null=True, verbose_name='특이사항2')),
                ('etc3', models.CharField(blank=True, max_length=100, null=True, verbose_name='특이사항3')),
                ('activation', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=5, verbose_name='활성화 여부')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트 날짜')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
        ),
    ]
