# Generated by Django 2.2.4 on 2020-02-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epost', '0002_cvsupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsupload',
            name='file',
            field=models.FileField(upload_to='epost/%Y/%m/%d', verbose_name='파일'),
        ),
    ]
