# Generated by Django 2.2.4 on 2020-06-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epost', '0003_auto_20200202_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingplan',
            name='call',
            field=models.IntegerField(verbose_name='음성'),
        ),
        migrations.AlterField(
            model_name='callingplan',
            name='data_category',
            field=models.IntegerField(verbose_name='데이터 기준'),
        ),
        migrations.AlterField(
            model_name='callingplan',
            name='message',
            field=models.IntegerField(verbose_name='문자'),
        ),
    ]
